pipeline{
    agent any
    environment{
        VERSION = "${currentBuild.number}"
        CREDS = credentials('docker')
    }
    stages{
        stage("docker build & docker push"){
            steps{
                dir("${env.WORKSPACE}/frontend"){
                script{
                        sh '''
                            docker build -t sha2121/empms-frontend:${VERSION} .
                            docker login -u sha2121 -p $CREDS
                            docker push  sha2121/empms-frontend:${VERSION}
                            docker rmi sha2121/empms-frontend:${VERSION}
                        '''
                    }
                }
            }
        }
    }
}