apiVersion: apps/v1
kind: Deployment
metadata:
  name: "empms-elasticsearch"
  namespace: "ot-microservices"
spec:
  selector:
    matchLabels:
      app: "empms-elasticsearch"
  replicas: 1
  template:
    metadata:
      labels:
        app: "empms-elasticsearch"
    spec:
      containers:
      - image: sha2121/empms-es:33
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 200Mi   
        name: "empms-elasticsearch"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: ES_JAVA_OPTS 
          value: -Xmx512m -Xms512m
        - name: ELASTIC_PASSWORD
          value: elastic
        envFrom:
        - configMapRef:
            name: es-config  
        volumeMounts:
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/data    
      volumes:
        - name: elasticsearch
          emptyDir: {}      
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: "ot-microservices"
spec:
  selector:
    app: empms-elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: http-2
      port: 9300
      targetPort: 9300  
  type: ClusterIP            
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: "ot-microservices"
data:
  cluster.name: "ot-microservices"
  network.host: "0.0.0.0"
  discovery.type: "single-node"
  xpack.license.self_generated.type: trial
  xpack.security.enabled: "true"
  xpack.monitoring.collection.enabled: "true"
