pipeline{
    agent any
    environment{
        VERSION = "${currentBuild.number}"
        CREDS = credentials('docker')
    }
    stages{
        stage("Deployment and Service Creation"){
            steps{
                dir("${env.WORKSPACE}/elasticsearch/k8s-manifests"){
                sshagent(['k8s']) {
                    sh 'kubectl apply -f deployment.yaml'
                }
                }
            }
        }
    }
}