apiVersion: apps/v1
kind: Deployment
metadata:
  name: "empms-frontend"
  namespace: "ot-microservices"
spec:
  selector:
    matchLabels:
      app: "empms-frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: "empms-frontend"
    spec:
      containers:
      - image: sha2121/empms-frontend:1
        imagePullPolicy: Always
        name: "empms-frontend"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 200Mi   
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: "ot-microservices"
spec:
  selector:
    app: empms-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP