apiVersion: apps/v1
kind: Deployment
metadata:
  name: "empms-gateway"
  namespace: "ot-microservices"
spec:
  selector:
    matchLabels:
      app: "empms-gateway"
  replicas: 1
  template:
    metadata:
      labels:
        app: "empms-gateway"
    spec:
      containers:
      - image: sha2121/empms-gateway:1
        imagePullPolicy: Always
        name: "empms-gateway"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 200Mi   
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: "ot-microservices"
spec:
  selector:
    app: empms-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP