pipeline{
    agent any
    environment{
        VERSION = "${currentBuild.number}"
    }
    stages{
        stage("docker build & docker push"){
            steps{
                dir("${env.WORKSPACE}/mysql"){
                script{
                    withCredentials([$class:'org.jenkinsci.plugins.plaincredentials.StringCredentials'(credentialsId: 'docker', variable: 'docker_password')]) {
                             sh '''
                                docker build -t sha2121/empms-db:${VERSION} .
                                docker login -u admin -p $docker_password 
                                docker push  sha2121/empms-db:${VERSION}
                                docker rmi sha2121/empms-db:${VERSION}
                            '''
                    }
                }
                }
            }
        }
    }
}